classdef CameraComponentProperties < handle
properties (Constant)
Data = struct(...
ID = struct( ... 
    default     = "", ...
    allowable   = {{}}, ... 
    validatefcn = @(x) true, ... 
    dependencies= @(propStruct) true, ...
    required    = @(propStruct) false, ...
    note        = "Only needed to distinguish between cameras"), ...
Adaptor = struct( ...
    default     = 'gentl', ... 
    allowable = imaqhwinfo().InstalledAdaptors, ...
    validatefcn = @(x) isstring(x) || ischar(x), ...
    dependencies= @(propStruct) true, ... 
    required    = @(propStruct) true, ...
    note        = "Any MATLAB-supported camera adaptor."), ...
Binning = struct( ...
    default     = 1, ...
    allowable   = {1, 2, 4}, ... 
    validatefcn = @(x) true, ...
    dependencies= @(propStruct) strcmpi(propStruct.Adaptor, 'gentl') || ...
                    strcmpi(propStruct.Adaptor, 'pcocameraadaptor'), ...
    required    = @(propStruct) true, ...
    note        = ""), ...
BinningType = struct( ...
    default     = "Sum", ...
    allowable   = {{}}, ... %TODO unknown as yet.
    validatefcn = @(x) true, ...
    dependencies= @(propStruct) strcmpi(propStruct.Adaptor, 'gentl') || ...
                    strcmpi(propStruct.Adaptor, 'pcocameraadaptor'), ... %copied and pasted from binning
    required    = @(propStruct) true, ...
    note        = ""), ...
ExposureTime = struct( ...
    default     = "10000", ...
    allowable   = {{}}, ...
    validatefcn = @(x) ~isNan(str2double(x)), ...
    dependencies= @(propStruct) true, ...
    required    = @(propStruct) false, ... 
    note        = "Only needed to distinguish between cameras"), ...
FramesPerTrigger = struct( ...
    default     = "1", ...
    allowable   = [], ...
    validatefcn = @(x) strcmpi(x, "1"), ...
    dependencies= @(propStruct) strcmpi(propStruct.TriggerMode, "hardware") || ...
                    strcmpi(propStruct.TriggerMode, "manual"), ...
    required    = @(propStruct) true, ... 
    note        = "Ideally any number will be permitted but not yet"), ...
Gain = struct( ...
    default     = "20", ...
    allowable   = {{}}, ...
    validatefcn = @(x) ~isNan(str2double(x)) && ...
                    str2double(x)>=0 && str2double(x)<=36, ...
    dependencies= @(propStruct) true, ...
    required    = @(propStruct) false, ... 
    note        = "dB. Max of 36."), ...
OutputLine = struct( ...
    default     = "Line3", ...
    allowable   = [], ...
    validatefcn = @(propStruct) true, ...
    dependencies= @(propStruct) strcmpi(propStruct.TriggerMode, "immediate"), ...
    required    = @(propStruct) false, ... 
    note        = "Depends on specific camera hardware."), ...
TriggerActivation = struct( ...
    default     = "RisingEdge", ...
    allowable   = [], ... %TODO
    validatefcn = @(propStruct) true, ... 
    dependencies= @(propStruct) strcmpi(propStruct.TriggerMode, "hardware"), ...
    required    = @(propStruct) false, ... 
    note        = "Depends on specific camera hardware."), ...
TriggerMode = struct( ...
    default     = "hardware", ...
    allowable   = {"hardware", "manual", "immediate"}, ...
    validatefcn = [], ...
    dependencies= @(propStruct) true, ...
    required    = @(propStruct) true, ... 
    note        = "hardware: GPIO-triggered, manual: software-triggered, " + ...
                    "immediate: camera-driven acquisition."), ...
TriggerFrameDelay = struct( ...
    default     = 0, ...
    allowable   = [], ...
    validatefcn = @(x) isnumeric(x), ...
    dependencies= @(propStruct) true, ...
    required    = @(propStruct) true, ... 
    note        = ""), ...
FrameGrabInterval = struct( ...
    default     = 10, ...
    allowable   = [], ...
    validatefcn = [], ...
    dependencies= @(propStruct) true, ...
    required    = @(propStruct) true, ... 
    note        = "Number of frames to have captured before " + ...
                    "activating framesavailable"), ...
TriggerRepeat = struct( ...
    default     = 100000000, ...
    allowable   = [], ...
    validatefcn = [], ...
    dependencies= @(propStruct) true, ...
    required    = @(propStruct) true, ... 
    note        = "Number of frames to capture before the camera closes itself. " + ...
                    "Ideally indefinite but I can't figure out how to do that"), ...
ROIPosition = struct( ...
    default     = [], ...
    allowable   = [], ...
    validatefcn = [], ...
    dependencies= @(propStruct) true, ...
    required    = @(propStruct) true, ... 
    note        = "ROI, set programmatically. If empty, defaults to full camera FOV"), ...
TriggerSelector = struct( ...
    default     = "FrameStart", ...
    allowable   = [], ... #TODO
    validatefcn = @(propStruct) true, ...
    dependencies= @(propStruct) strcmpi(propStruct.TriggerMode, "hardware") || ...
                    strcmpi(propStruct.TriggerMode, "manual"), ...
    required    = @(propStruct) true, ... 
    note        = ""))
end
end