classdef CameraComponentProperties < ComponentProperties
properties (Constant)
Data = struct( ...
    ID = ComponentProperty( ...
        'default', '', ...
        'required', false, ...
        'note', 'Only needed to distinguish between cameras'), ...
    Adaptor = ComponentProperty( ...
        'default'     , 'gentl', ... 
        'allowable' , imaqhwinfo().InstalledAdaptors, ...
        'validatefcn' , @(x) isstring(x) || ischar(x), ...
        'dependents'  , {'Binning', 'BinningType'}, ...
        'note'        , 'Any MATLAB-supported camera adaptor.'), ...
    Binning = ComponentProperty( ...
        'default'     , 1, ...
        'allowable'   , [1, 2, 4], ...
        'dynamic'     , false, ...
        'dependencies', @(propStruct) strcmpi(propStruct.Adaptor, 'gentl') || ...
                        strcmpi(propStruct.Adaptor, 'pcocameraadaptor')), ...
    BinningType = ComponentProperty( ...
        'default'     , 'Sum', ...
        'allowable'   , {'Sum', 'Other'}, ... %TODO unknown as yet.
        'dynamic'     , false, ...
        'dependencies', @(propStruct) strcmpi(propStruct.Adaptor, 'gentl') || ...
                        strcmpi(propStruct.Adaptor, 'pcocameraadaptor') ... %copied and pasted from binning
        ), ...
    ExposureTime = ComponentProperty( ...
        'default'     , '10000', ...
        'validatefcn' , @(x) ~isnan(str2double(x)), ...
        'dynamic'     , true, ...
        'note'        , ''), ...
    FramesPerTrigger = ComponentProperty( ...
        'default'     , '1', ...
        'validatefcn' , @(x) strcmpi(x, '1'), ...
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'hardware') || ...
                        strcmpi(propStruct.TriggerMode, 'manual'), ...
        'dynamic'     , true, ...
        'note'        , 'Ideally any number will be permitted but not yet'), ...
    Gain = ComponentProperty( ...
        'default'     , '20', ...
        'validatefcn' , @(x) ~isnan(str2double(x)) && ...
                        str2double(x)>=0 && str2double(x)<=36, ...
        'dynamic'     , true, ...
        'note'        , 'dB. Max of 36.'), ...
    OutputLine = ComponentProperty( ...
        'default'     , 'Line3', ...
        'allowable'   , {'Line3', 'Line4'}, ...
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'immediate'), ...
        'dynamic'     , true, ...
        'note'        , 'Depends on specific camera hardware.'), ...
    TriggerActivation = ComponentProperty( ...
        'default'     , 'RisingEdge', ...
        'allowable'   , {'RisingEdge', 'FallingEdge', 'none'}, ... %TODO
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'hardware'), ...
        'dynamic'     , false, ...
        'note'        , 'Depends on specific camera hardware.'), ...
    TriggerMode = ComponentProperty( ...
        'default'     , 'manual', ...
        'allowable'   , {'hardware', 'manual', 'immediate'}, ...
        'dynamic'     , false, ...
        'dependents'  , {'TriggerActivation', 'TriggerSelector', 'FramesPerTrigger', 'OutputLine'}, ...
        'note'        , ['hardware: GPIO-triggered, manual: software-triggered, ', ...
                        'immediate: camera-driven acquisition.']), ...
     TriggerLine = ComponentProperty( ...
        'default'     , 'Line4', ...
        'allowable'   , {'Line3', 'Line4'}, ... %TODO
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'hardware'), ...
        'dynamic'     , true, ...
        'note'        , 'Depends on specific camera hardware.'), ...
    TriggerFrameDelay = ComponentProperty( ...
        'default'     , 0, ...
        'validatefcn' , @(x) isnumeric(x), ...
        'dynamic'     , true), ...
    FrameGrabInterval = ComponentProperty( ...
        'default'     , 10, ...
        'allowable'   , [], ...
        'validatefcn' , @(x) isnumeric(x) && x > 0, ...
        'dynamic'     , true, ...
        'note'        , ['Number of frames to have captured before ', ...
                        'activating framesavailable']), ...
    TriggerRepeat = ComponentProperty( ...
        'default'     , 100000000, ...
        'validatefcn' , @(x) isnumeric(x) && x > 0, ...
        'dynamic'     , false, ...
        'note'        , ['Number of frames to capture before the camera closes itself. ', ...
                        'Ideally indefinite but unclear if that is supported']), ...
    ROIPosition = ComponentProperty( ...
        'default'     , '', ...
        'validatefcn' , @(x) (ischar(x) || isstring(x)) && (isempty(x) || any(regexpi(x, "^(\d+( )){3}\d+$"))), ...
        'dynamic'     , false, ...
        'note'        , 'ROI, set programmatically. If empty, defaults to full camera FOV'), ...
    TriggerSelector = ComponentProperty( ...
        'default'     , 'FrameStart', ...
        'allowable'   , [], ... #TODO
        'dynamic'     , false, ...
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'hardware') || ...
                        strcmpi(propStruct.TriggerMode, 'manual')));
    % ComponentID = ComponentProperty( ...
    %     'default'     , obj.GetComponentID, ...
    %     'validatefcn', @(x) isstring(x) || ischar(x), ...
    %     'dynamic'     , false));
end

methods
    % function out = GetComponentID(obj)
    %     obj.Data.
    % end
end
end