classdef DAQComponentProperties < ComponentProperties
properties (Constant)
Data = struct( ...
    ID = ComponentProperty( ...
        'default', 'Dev1', ...
        'allowable', {daqlist().DeviceInfo.ID}), ...
    Rate = ComponentProperty( ...
        'default', 1000, ...
        'validatefcn', @(x) isnumeric(x) && x > 0, ...
        'note', 'Sampling rate in Hz'), ...
    Vendor = ComponentProperty( ...
        'default', 'ni', ...
        'allowable', unique(cellfun(@(x) x.ID, {daqlist().DeviceInfo.Vendor}, 'UniformOutput', false)), ...
        'note', 'Used to initialise'), ...
    Model = ComponentProperty( ...
        'default', '', ...
        'allowable', {daqlist().DeviceInfo.Model}, ...
        'note', 'Distinguishes between multiple daqs with the same vendor'))
end
end