classdef DAQComponentProperties < ComponentProperties
properties (Constant)
Data = struct( ...
    ID = ComponentProperty( ...
        'default', 'Dev1', ...
        'allowable', {daqlist().DeviceInfo.ID}), ...
    Rate = ComponentProperty( ...
        'default', 1000, ...
        'validatefcn', @(x) (isnumeric(x) && x > 0) || ~isnan(str2double(x)) && str2double(x)>=0, ...
        'note', 'Sampling rate in Hz'), ...
    Vendor = ComponentProperty( ...
        'default', 'ni', ...
        'allowable', unique(cellfun(@(x) x.ID, {daqlist().DeviceInfo.Vendor}, 'UniformOutput', false)), ...
        'note', 'Used to initialise'), ...
    Model = ComponentProperty( ...
        'default', '', ...
        'allowable', {daqlist().DeviceInfo.Model}, ...
        'note', 'Distinguishes between multiple daqs with the same vendor'), ...
    ChannelConfig = ComponentProperty( ...
        'validatefcn', @(x) isstring(x) || ischar(x), ...
        'default', DAQComponentProperties.GetDefaultChannelConfig))
end
methods (Static, Access=private)
    function out = GetDefaultChannelConfig()
        %DEBUG: TODO REMOVE
        [s, out] = system('vol');
        out = strsplit(out, '\n');
        out = out{2}(end-8:end);
        if strcmpi(out, '48AC-D74C')
            filename = 'Minimal_LaserRoom_DaqChanParams.csv';
        else
            filename = 'Minimal_OuterLab_DaqChanParams.csv';
        end
        %END DEBUG
        if contains(pwd, 'StimControl')
            out = [pwd filesep 'config' filesep 'component_params' filesep filename];
        else
            out = [pwd filesep 'StimControl' filesep 'config' filesep 'component_params' filesep filename];
        end
    end
end
end