function createFigure(obj)
% https://au.mathworks.com/help/matlab/creating_guis/choose-components-for-your-app-designer-app.html
% https://au.mathworks.com/help/matlab/creating_guis/create-and-run-a-simple-programmatic-app.html
% https://au.mathworks.com/help/matlab/develop-apps-programmatically.html?s_tid=CRUX_lftnav
obj.h.fig = uifigure(...
    'Position',         [100,0,1092,657], ...
    'Units',            'Pixels', ...
    'Name',             obj.name, ...
    'CloseRequestFcn',  @obj.callbackFileExit, ...
    'GraphicsSmoothing','on');

%% Make base tabs and grids
obj.h.baseGrid = uigridlayout(obj.h.fig, ...
    'RowHeight', {'1x'}, ...
    'ColumnWidth', {'1x'});
obj.h.tabs = uitabgroup(obj.h.baseGrid, ...
    'SelectionChangedFcn', @obj.callbackChangeTab);

%% create menu
obj.h.menuDebug      = uimenu(obj.h.fig, ...
    'Label',        'Debug', ...
    'Callback',     @(src, event)obj.callbackDebug(src, event));

%% Setup Tab
obj.h.Setup.Tab = uitab(obj.h.tabs, 'Title', 'Setup');
obj.h.Setup.Grid = uigridlayout(obj.h.Setup.Tab, ...
    'RowHeight', {'1x', 180, 70}, ...
    'ColumnWidth', {'1x', 250});

obj.h.Setup.Control.panel.params = uipanel(obj.h.Setup.Grid, ...
    'CreateFcn', @obj.createPanelSetupControl, ...
    'Title', 'Setup', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', [2 3], ...
        'Column',1));
obj.h.Setup.Preview.panel.params = uipanel(obj.h.Setup.Grid, ...
    'CreateFcn', @obj.createPanelSetupPreview, ...
    'Title', 'Preview', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column',1));
obj.h.Setup.ComponentConfig.panel.params = uipanel(obj.h.Setup.Grid, ...
    'CreateFcn', @obj.createPanelComponentConfig, ...
    'Title', 'Component Config', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', [1, 2], ...
        'Column', 2));
obj.h.Setup.Logo = uiimage(obj.h.Setup.Grid, ...
    "ImageSource", [obj.path.base filesep '@StimControl' filesep 'icons' filesep 'WhitmireLogo.png'], ...
    "ScaleMethod", "fit", ...
    "Layout", matlab.ui.layout.GridLayoutOptions( ...
        'Row',3, ...
        'Column',2));

%% Session Tab
obj.h.Session.Tab = uitab(obj.h.tabs, 'Title', 'Experiment');
obj.h.Session.Grid = uigridlayout(obj.h.Session.Tab, ...
    'RowHeight', {'1x', 100}, ...
    'ColumnWidth', {'1x', 250});

obj.h.Session.Control.panel.params = uipanel(obj.h.Session.Grid, ...
    'CreateFcn', @obj.createPanelSessionControl, ...
    'Title', 'Session Controls', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', 2));
obj.h.Session.HardwareStatus.panel.params = uipanel(obj.h.Session.Grid, ...
    'CreateFcn', @obj.createPanelSessionHardware, ...
    'Title', 'Component Status', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 2, ...
        'Column', 1));
obj.h.Session.Preview.panel.params = uipanel(obj.h.Session.Grid, ...
    'CreateFcn', @obj.createPanelSessionPreview, ...
    'Title', 'View', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', 1));
obj.h.Session.Logo = uiimage(obj.h.Session.Grid, ...
    "ImageSource", [obj.path.base filesep '@StimControl' filesep 'icons' filesep 'WhitmireLogo.png'], ...
    "ScaleMethod", "fit", ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 2, ...
        'Column', 2));

% % create LED panel
% obj.h.LED.panel.params = uipanel(obj.h.fig,...
% 	'CreateFcn',        @obj.createPanelLED);
% 
% % create thermode panels
% for ii = fliplr(1:length(obj.s))
%     thermodeID = ['Thermode' char(64+ii)];
%     obj.h.(thermodeID).panel.params = uipanel(obj.h.fig,...
%         'CreateFcn',    {@obj.createPanelThermode,ii,length(obj.s)});
% end
% 
% % synchronize axes
% tmp = fieldnames(obj.h);
% tmp = tmp(~cellfun(@(x) isempty(regexp(x,'^Thermode|LED','once')),tmp));
% linkaxes(cellfun(@(x) obj.h.(x).axes,tmp),'x')
% 
% % create remaining panels
% obj.h.animal.panel.main      = uipanel(obj.h.fig,...
%     'CreateFcn',    @obj.createPanelAnimal);
% obj.h.protocol.panel.main    = uipanel(obj.h.fig,...
%     'CreateFcn',    @obj.createPanelProtocol);
% obj.h.singleRun.panel.main    = uipanel(obj.h.fig,...
%     'CreateFcn',    @obj.createPanelSingleRun);
% 
% % resize figure
% obj.h.fig.Position(4) = sum(obj.h.singleRun.panel.main.Position([2 4]))+10;
% 
% % create menu
% obj.h.menu.file     = uimenu(...
%     'Label',        'File');
% obj.h.menu.fileOpen	= uimenu(obj.h.menu.file,...
%     'Label',        'Open ...', ...
%     'Accelerator',  'O', ...
%     'Callback',     @obj.callbackFileOpen);
% obj.h.menu.fileClose= uimenu(obj.h.menu.file,...
%     'Label',        'Close', ...
%     'Enable',       'Off', ...
%     'Callback',     @obj.callbackFileClose);
% obj.h.menu.fileExit	= uimenu(obj.h.menu.file,...
%     'Label',        'Exit', ...
%     'Separator',    'on', ...
%     'Callback',     @obj.callbackFileExit);
% obj.h.menu.debug 	= uimenu(...
%     'Label',        'Debug');
% obj.h.menu.debugKB	= uimenu(obj.h.menu.debug,...
%     'Label',        'Keyboard', ...
%     'Callback',     @obj.callbackDebugKB);
% obj.h.menu.debugCB  = uimenu(obj.h.menu.debug,...
%     'Label',        'Copy Parameters', ...
%     'Callback',     @obj.callbackDebugCB);
% obj.h.menu.debugDel = uimenu(obj.h.menu.debug,...
%     'Label',        'Delete Unused Animal IDs', ...
%     'Callback',     @obj.callbackDebugDelEmpty);
% 
% obj.h = orderfields(obj.h);
% movegui(obj.h.fig,'center')
% obj.h.fig.Visible = 'on';