function createPanelSessionControl(obj, hPanel, ~)

grid = uigridlayout(hPanel);
grid.RowHeight = {22, 22, '0.1x', 22, 22, '0.1x', 22, 22, '0.1x', 50, '1x'};
grid.ColumnWidth = {22, '1x', '0.5x', '0.5x', '1x', 22};
% grid.RowSpacing = 2;
nCols = length(grid.ColumnWidth);
nRows = length(grid.RowHeight);

%% create animal select section
aRow = 1;
obj.h.animalLabel = uilabel(grid, 'Text', 'Animal ID', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', aRow, ...
        'Column', [1 nCols]));

obj.h.animalSelectDropDown = uidropdown(grid, ...
    'Editable', 'on', 'Items', getFilesList(obj.path.dirData, ''), ...
    'ValueChangedFcn', @obj.callbackSelectAnimal, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', aRow + 1, ...
        'Column', [1 nCols-1]));

obj.h.newAnimalBtn = uibutton(grid, ...
    'ButtonPushedFcn', @obj.callbackNewAnimal, ...
    'Text', '+', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', aRow + 1, ...
        'Column', nCols));

%% Create experiment / protocol select section
protRow = aRow + 3;
obj.h.protocolNameLabel = uilabel(grid, 'Text', 'Protocol', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', protRow, ...
        'Column', [1 floor(nCols/2)]));

obj.h.protocolTimeEstimateLabel = uilabel(grid, 'Text', '00:00:00', ...
    'HorizontalAlignment', 'right', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', aRow + 1, ...
        'Column', [ceil(nCols/2) nCols]));

protocolFilesList = getFilesList(obj.path.protocolBase, '.stim');
obj.h.protocolSelectDropDown = uidropdown(grid, ...
    'Editable', 'on', 'Items', [protocolFilesList{2:end} {'Browse...'}], ...
    'ValueChangedFcn', @obj.callbackLoadProtocol, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', protRow + 1, ...
        'Column', [1 nCols-1]));

% newProtocolBtn = uibutton(grid, ...
%     'ButtonPushedFcn', @obj.callbackNewProtocol, ...
%     'Text', '+');
% newProtocolBtn.Layout.Row = protRow + 1;
% newProtocolBtn.Layout.Column = nCols;

%% create trial select section
tRow = protRow + 3;
obj.h.trialLabel = uilabel(grid, 'Text', 'Trial', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow, ...
        'Column', [1 floor(nRows/2)]));
obj.h.trialTimeEstimate = uilabel(grid, 'Text', '00:00:00', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow, ...
        'Column', [ceil(nRows/2) nRows]));

obj.h.prevTrialBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event)obj.callbackUpdateTrialNum(src, event), ...
    'Text', '<', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow + 1, ...
        'Column', 1));

obj.h.nextTrialBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event)obj.callbackUpdateTrialNum(src, event), ...
    'Text', '>', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow + 1, ...
        'Column', nCols));

obj.h.totalTrialsLabel = uilabel(grid, ...
    'Text', '/Total', 'HorizontalAlignment', 'Left', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow + 1, ...
        'Column', [ceil(nRows/2) nRows-1]));

obj.h.trialNumDisplay = uieditfield(grid, 'numeric', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow + 1, ...
        'Column', [2 floor(nRows/2)]));

%% create start/stop buttons
sessionCtrlRow = tRow + 3;

obj.h.startStopExperimentBtn = uibutton(grid, ...
    'Text', 'START', 'WordWrap', 'on', ...
    'ButtonPushedFcn', @obj.callbackSessionStart, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', sessionCtrlRow, ...
        'Column', [1 2]), ...
    'Enable', 'off');

obj.h.pauseBtn = uibutton(grid, ...
    'Text', 'PAUSE', 'WordWrap', 'on', ...
    'ButtonPushedFcn', @obj.callbackSessionPause, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', sessionCtrlRow, ...
        'Column', [3 nCols-2]), ...
    'Enable', 'off');

obj.h.singleStimBtn = uibutton(grid, ...
    'Text', 'Single Stim', 'WordWrap', 'on', ...
    'ButtonPushedFcn', @obj.callbackSingleStim, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', sessionCtrlRow, ...
        'Column', [nCols-1 nCols]), ...
    'Enable', 'off');

%% create information panel
sessionInformationPanel = uipanel(grid, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', nRows, ...
        'Column', [1 nCols]));

infoGrid = uigridlayout(sessionInformationPanel, ...
    'RowHeight', {23, 23, 23, '1x'}, ...
    'ColumnWidth', {23, '1x', '1x', 23});
niRows = length(infoGrid.RowHeight);
niCols = length(infoGrid.ColumnWidth);

obj.h.statusLamp = uilamp(infoGrid, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', 1), ...
    'Color', 'red');

obj.h.statusLabel = uilabel(infoGrid, ...
    'Text', 'SELECT EXPERIMENT', 'HorizontalAlignment', 'left', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', 2));

obj.h.StatusCountdownLabel = uilabel(infoGrid, ...
    'Text', '-00:00', 'HorizontalAlignment', 'right', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', [3 4]));

obj.h.TrialTimerLabel = uilabel(infoGrid, ...
    'Text', '00:00/00:00', 'HorizontalAlignment', 'left', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 2, ...
        'Column', [1 2]));

obj.h.ProtocolTimerLabel = uilabel(infoGrid, ...
    'Text', '00:00', 'HorizontalAlignment', 'right', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 2, ...
        'Column', [3 4]));

obj.h.numTrialsElapsedLabel = uilabel(infoGrid, ...
    'Text', 'Trials: 0/0', 'HorizontalAlignment', 'left', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', niRows-1, ...
        'Column', [1 niCols]));

obj.h.trialInformationScroller = uitextarea(infoGrid, ...
    'Editable', 'off', ...
    'Value', {"1(3): comment stim3", "2(1): comment stim1", "3(2): comment stim2"}, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', niRows, ...
        'Column', [1 niCols]));

obj.h.sessionInformationPanel.panel.params = sessionInformationPanel;
end