function createPanelSetupControl(obj, hPanel, ~)
grid = uigridlayout(hPanel);
grid.RowHeight = {'1x', '0.01x', 22, 22};
grid.ColumnWidth = {100, 23, 23, 100, 23, 23, 100, 23, '1x', 90};
grid.RowSpacing = 2;
saveIcon = [obj.path.base filesep '@StimControl' filesep 'icons' filesep 'save.png'];

%% create StimControl session select
scCol = 1;
sessionConfigFilesList = getFilesList(obj.path.sessionBase, '.json');
obj.h.SessionSelectDropDown= uidropdown(grid, ...
    'Editable', 'on', 'Items', [{'Auto'} {'Browse...'} sessionConfigFilesList{2:end}], ...
    'ValueChangedFcn', @(src, event) obj.callbackLoadConfig(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', scCol));

obj.h.saveSessionBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event) obj.callbackSaveConfig(src, event), ...
    'Icon', saveIcon, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', scCol + 1));

sessionLabel = uilabel(grid, 'Text', 'Session Config', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight) - 1, ...
        'Column', [scCol scCol+1]));

%% create hardware config select
ccCol = scCol + 3;
componentConfigFilesList = getFilesList(obj.path.paramBase, '.json');
obj.h.ComponentConfigDropDown = uidropdown(grid, ...
    'Editable', 'on', 'Items', [{'Auto'} {'Browse...'} componentConfigFilesList{2:end}], ...
    'ValueChangedFcn', @(src, event) obj.callbackLoadConfig(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', ccCol));

obj.h.createConfigBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event) obj.callbackSaveConfig(src, event), ...
    'Icon', saveIcon, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', ccCol + 1));

configLabel = uilabel(grid, 'Text', 'Hardware Config', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight) - 1, ...
        'Column', [ccCol ccCol+1]));

%% create component edit button
obj.h.editComponentConfigBtn = uibutton(grid, ...
    'WordWrap', 'on', 'Text', 'Edit Component', ...
    'ButtonPushedFcn',@(src, event)obj.callbackEditComponentConfig(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', [length(grid.RowHeight) - 1, length(grid.RowHeight)], ...
        'Column', length(grid.ColumnWidth)));

%% Create Component Table
obj.h.AvailableHardwareTable = uitable('Parent', grid, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', [1 length(grid.ColumnWidth)]), ...
    'ColumnSortable', true, ...
    'SelectionType', 'row', ...
    'ColumnEditable', [false false true false true true], ...
    'SelectionChangedFcn', @obj.callbackEditComponentConfig, ...
    'CellEditCallback', @(src, event) updateComponentTableCell(src, event, obj));

%% Populate Component Table
columnNames = {'Type', 'ID', 'Protocol ID', 'Status', 'Enable', 'Preview'};
tData = table();
available = obj.d.Available;
if isempty(obj.d.Available) % prevent errors with no hardware attached
    return
end
for i = 1:length(obj.d.Available)
    device = obj.d.Available{i};
    tData(end+1, :) = {class(device), ...
                        device.ComponentID, ...
                        device.ConfigStruct.ProtocolID, ...
                        device.GetStatus, ...
                        ~isempty(device.SessionHandle), ...
                        device.Previewing};
end

tData.Properties.VariableNames = columnNames;
obj.h.AvailableHardwareTable.Data = tData;
end

%% UPDATE FUNCTIONS
function updateComponentTableCell(src, event, obj)
    idxRow = event.Indices(1);
    property = src.Data.Properties.VariableNames(event.Indices(2));
    component = obj.d.Available{idxRow};
    if strcmpi(property, "Protocol ID")
        component.SetParam("ProtocolID", event.NewData);
        % TODO REFRESH BUTTON
        obj.d.ProtocolIDMap = remove(obj.d.ProtocolIDMap, event.PreviousData);
        obj.d.ProtocolIDMap(event.NewData) = idxRow;
    elseif strcmpi(property, "Enable")
        if event.NewData
            obj.d.Active(idxRow) = true;
            component.InitialiseSession();
        else
            obj.d.Active(idxRow) = false;
            component.Stop();
        end
    elseif strcmpi(property, "Preview")
        if event.NewData    
            component.StartPreview();
        else
            component.StopPreview();
        end
    end
end