function createPanelSetupControl(obj, hPanel, ~)
grid = uigridlayout(hPanel);
grid.RowHeight = {'1x', '0.01x', 22, 22};
grid.ColumnWidth = {100, 23, 23, 100, 23, 23, 100, 23, '1x', 90};
grid.RowSpacing = 2;

%% create debug button
debugBtn = uibutton(grid, ...
    'WordWrap', 'on', 'Text', 'DEBUG', ...
    'ButtonPushedFcn',@(src, event) obj.callbackDebug, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', [length(grid.RowHeight) - 1, length(grid.RowHeight)], ...
        'Column', length(grid.ColumnWidth) - 1));

%% create hardware config select
ccCol = 1;
obj.h.ComponentConfigDropDown = uidropdown(grid, ...
    'Editable', 'on', 'Items', getFilesList(obj.path.paramBase, '.json'), ...
    'ValueChangedFcn', @obj.callbackLoadParams, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', ccCol));

createConfigBtn = uibutton(grid, ...
    'ButtonPushedFcn', @obj.callbackCreateParams, ...
    'Text', '+', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', ccCol + 1));

configLabel = uilabel(grid, 'Text', 'Hardware Config', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight) - 1, ...
        'Column', [ccCol ccCol+1]));

%% create StimControl session select
scCol = 4;
obj.h.SessionSelectDropDown= uidropdown(grid, ...
    'Editable', 'on', 'Items', getFilesList(obj.path.sessionBase, '.json'), ...
    'ValueChangedFcn', @obj.callbackLoadSession, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', scCol));

saveSessionBtn = uibutton(grid, ...
    'ButtonPushedFcn', @obj.callbackSaveSession, ...
    'Text', '+', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', scCol + 1));

sessionLabel = uilabel(grid, 'Text', 'Session Config', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight) - 1, ...
        'Column', [scCol scCol+1]));

%% Create BasePath select
bpCol = 7;
obj.h.PathSelectDropDown = uidropdown(grid, ...
    'Editable', 'on', 'Items', getFilesList(obj.path.dirData, ''), ... %TODO THIS IS WRONG
    'ValueChangedFcn', @obj.callbackChangeBasePath, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', bpCol));

browseBasePathBtn = uibutton(grid, ...
    'ButtonPushedFcn', @obj.callbackNewPath, ...
    'Text', '+', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', bpCol + 1));

basePathLabel = uilabel(grid, 'Text', 'SavePath', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight) - 1, ...
        'Column', [bpCol bpCol+1]));

%% create component edit button
editComponentConfigBtn = uibutton(grid, ...
    'WordWrap', 'on', 'Text', 'Edit Component', ...
    'ButtonPushedFcn',@(src, event) obj.callbackEditComponentConfig, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', [length(grid.RowHeight) - 1, length(grid.RowHeight)], ...
        'Column', length(grid.ColumnWidth)));

%% Create Component Table
obj.d.AvailableHardwareTable = uitable('Parent', grid, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', [1 length(grid.ColumnWidth)]), ...
    'ColumnSortable', true, ...
    'SelectionType', 'row', ...
    'ColumnEditable', [false false false true ], ...
    'CellEditCallback', @(src, event) updateComponentTableCell(src, event, obj));

%% Populate Component Table
columnNames = {'Type', 'ID', 'Status', 'Enable'};
tData = table();
available = obj.d.Available;
for i = 1:length(obj.d.Available)
    device = obj.d.Available{i};
    tData(end+1, :) = {class(device), device.ComponentID, device.GetStatus, ~isempty(device.SessionHandle)};
end

tData.Properties.VariableNames = columnNames;
obj.d.AvailableHardwareTable.Data = tData;
end

%% UPDATE FUNCTIONS
function updateComponentTableCell(src, event, obj)
    rowIndex = event.Indices(1);
    component = obj.d.Available{rowIndex};
    if event.NewData
        obj.d.Active{rowIndex} = true;
        component.InitialiseSession();
        component.StartPreview();
    else
        obj.d.Active{rowIndex} = false;
        component.StopPreview();
        % TODO de-initialise if needed?
    end
end