function createPanelSetupPreview(obj, hPanel, ~)
numComponents = length(obj.d.Available);
numRows = floor(sqrt(numComponents));
numCols = ceil(numComponents/numRows);

obj.h.Setup.PreviewGrid = uigridlayout(hPanel);
if numRows > 1
    obj.h.Setup.PreviewGrid.RowHeight = repmat("1x", [1 numRows]);
    rowSpan = [1 numRows];
else
    obj.h.Setup.PreviewGrid.RowHeight = {'1x'};
    rowSpan = 1;
end
if numCols > 1
    obj.h.Setup.PreviewGrid.ColumnWidth = repmat("1x", [1 numCols]);
    colSpan = [1 numCols];
else
    obj.h.Setup.PreviewGrid.ColumnWidth = {'1x'};
    colSpan = 1;
end
obj.h.Setup.PreviewPanels = {};
% obj.h.Setup.FullscreenPreviewAxes = uiaxes( ...
%             obj.h.Setup.PreviewGrid, ...
%             'Layout', matlab.ui.layout.GridLayoutOptions( ...
%                 'Row', rowSpan, ...
%                 'Column', colSpan), ...
%             'Visible', false);
% obj.h.Setup.FullscreenPreviewAxes.Title.String = "Preview";
doNothing = @(x,y,z) true;
for i = 1:numRows
    for j = 1:numCols
        componentIdx = ((i-1) * numCols) + j;
        if length(obj.d.Available) < componentIdx
            return
        end
        panel = uipanel(obj.h.Setup.PreviewGrid, ...
            'CreateFcn', doNothing,...
            'Layout', matlab.ui.layout.GridLayoutOptions( ...
                'Row', i, ...
                'Column', j));
        panelGrid = uigridlayout(panel, ...
            'RowHeight', {'1x'}, ...
            'ColumnWidth', {'1x'});
        ax = uiaxes(panelGrid, ...
            'Layout', matlab.ui.layout.GridLayoutOptions( ...
                'Row', 1, ...
                'Column', 1), ...
            'Layout', matlab.ui.layout.GridLayoutOptions( ...
                'Row', i, ...
                'Column', j), ...
            'XTick', [], ...
            'XTickLabel', [], ...
            'YTick', [], ...
            'YTickLabel', []);
        component = obj.d.Available{componentIdx};
        panel.Title = component.ConfigStruct.ProtocolID;
        obj.h.Setup.PreviewPanels{end+1} = ax;
        component.UpdatePreview(obj.h.Setup.PreviewPanels{end});
    end
end